const {
  DIRECTION_NONE,
  DIRECTION_LEFT,
  DIRECTION_RIGHT
} = require('./create-relationship-statement')

const UNDIRECTED_GRAPH = 'graph'
const DIRECTED_GRAPH = 'digraph'
const RELATIONSHIP_TYPE_DEFAULT = 'CONNECTED_TO'

const GENERIC_NODE_TYPE = 'Node'
const GENERIC_RELATIONSHIP_TYPE = 'Relationship'
const DEFAULT_ID_NAME = 'id'

module.exports = {
  DIRECTION_NONE,
  DIRECTION_RIGHT,
  DIRECTION_LEFT,
  UNDIRECTED_GRAPH,
  DIRECTED_GRAPH,
  RELATIONSHIP_TYPE_DEFAULT,
  GENERIC_NODE_TYPE,
  GENERIC_RELATIONSHIP_TYPE,
  DEFAULT_ID_NAME
}
